In [1]:
import numpy as np
import pandas as pd

import seaborn as sns

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
df.sample(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
104,105,6.5,3.0,5.8,2.2,Iris-virginica
99,100,5.7,2.8,4.1,1.3,Iris-versicolor
125,126,7.2,3.2,6.0,1.8,Iris-virginica
32,33,5.2,4.1,1.5,0.1,Iris-setosa
113,114,5.7,2.5,5.0,2.0,Iris-virginica
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
39,40,5.1,3.4,1.5,0.2,Iris-setosa
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
15,16,5.7,4.4,1.5,0.4,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa

In [4]:
df = df.loc[df['Species']!='Iris-setosa']
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df.loc[df['Species'] == "Iris-virginica", "Species"] = 0
df.loc[df["Species"] == "Iris-versicolor", "Species"] = 1
df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
50    51            7.0           3.2            4.7           1.4       1
51    52            6.4           3.2            4.5           1.5       1
52    53            6.9           3.1            4.9           1.5       1
53    54            5.5           2.3            4.0           1.3       1
54    55            6.5           2.8            4.6           1.5       1
..   ...            ...           ...            ...           ...     ...
145  146            6.7           3.0            5.2           2.3       0
146  147            6.3           2.5            5.0           1.9       0
147  148            6.5           3.0            5.2           2.0       0
148  149            6.2           3.4            5.4           2.3       0
149  150            5.9           3.0            5.1           1.8       0

[100 rows x 6 columns]

In [7]:
df.shape

(100, 6)

In [8]:
x = df.iloc[:,1:5]
x.reset_index(drop=True, inplace = True)

In [9]:
x

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0             7.0           3.2            4.7           1.4
1             6.4           3.2            4.5           1.5
2             6.9           3.1            4.9           1.5
3             5.5           2.3            4.0           1.3
4             6.5           2.8            4.6           1.5
..            ...           ...            ...           ...
95            6.7           3.0            5.2           2.3
96            6.3           2.5            5.0           1.9
97            6.5           3.0            5.2           2.0
98            6.2           3.4            5.4           2.3
99            5.9           3.0            5.1           1.8

[100 rows x 4 columns]

In [10]:
x.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     100.000000    100.000000     100.000000    100.000000
mean        6.262000      2.872000       4.906000      1.676000
std         0.662834      0.332751       0.825578      0.424769
min         4.900000      2.000000       3.000000      1.000000
25%         5.800000      2.700000       4.375000      1.300000
50%         6.300000      2.900000       4.900000      1.600000
75%         6.700000      3.025000       5.525000      2.000000
max         7.900000      3.800000       6.900000      2.500000

In [11]:
x = (x - x.min())/(x.max() - x.min()) # this normalization is performes column wise
x

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        0.700000      0.666667       0.435897      0.266667
1        0.500000      0.666667       0.384615      0.333333
2        0.666667      0.611111       0.487179      0.333333
3        0.200000      0.166667       0.256410      0.200000
4        0.533333      0.444444       0.410256      0.333333
..            ...           ...            ...           ...
95       0.600000      0.555556       0.564103      0.866667
96       0.466667      0.277778       0.512821      0.600000
97       0.533333      0.555556       0.564103      0.666667
98       0.433333      0.777778       0.615385      0.866667
99       0.333333      0.555556       0.538462      0.533333

[100 rows x 4 columns]

In [12]:
y = df.iloc[:,-1]
# y.reset_index(drop=True, inplace=True)
y

50     1
51     1
52     1
53     1
54     1
      ..
145    0
146    0
147    0
148    0
149    0
Name: Species, Length: 100, dtype: object

In [13]:
x = x.values # converting into nupmy array
x

array([[0.7       , 0.66666667, 0.43589744, 0.26666667],
       [0.5       , 0.66666667, 0.38461538, 0.33333333],
       [0.66666667, 0.61111111, 0.48717949, 0.33333333],
       [0.2       , 0.16666667, 0.25641026, 0.2       ],
       [0.53333333, 0.44444444, 0.41025641, 0.33333333],
       [0.26666667, 0.44444444, 0.38461538, 0.2       ],
       [0.46666667, 0.72222222, 0.43589744, 0.4       ],
       [0.        , 0.22222222, 0.07692308, 0.        ],
       [0.56666667, 0.5       , 0.41025641, 0.2       ],
       [0.1       , 0.38888889, 0.23076923, 0.26666667],
       [0.03333333, 0.        , 0.12820513, 0.        ],
       [0.33333333, 0.55555556, 0.30769231, 0.33333333],
       [0.36666667, 0.11111111, 0.25641026, 0.        ],
       [0.4       , 0.5       , 0.43589744, 0.26666667],
       [0.23333333, 0.5       , 0.15384615, 0.2       ],
       [0.6       , 0.61111111, 0.35897436, 0.26666667],
       [0.23333333, 0.55555556, 0.38461538, 0.33333333],
       [0.3       , 0.38888889, 0.28205128, 0.        ],
       [0.43333333, 0.11111111, 0.38461538, 0.33333333],
       [0.23333333, 0.27777778, 0.23076923, 0.06666667],
       [0.33333333, 0.66666667, 0.46153846, 0.53333333],
       [0.4       , 0.44444444, 0.25641026, 0.2       ],
       [0.46666667, 0.27777778, 0.48717949, 0.33333333],
       [0.4       , 0.44444444, 0.43589744, 0.13333333],
       [0.5       , 0.5       , 0.33333333, 0.2       ],
       [0.56666667, 0.55555556, 0.35897436, 0.26666667],
       [0.63333333, 0.44444444, 0.46153846, 0.26666667],
       [0.6       , 0.55555556, 0.51282051, 0.46666667],
       [0.36666667, 0.5       , 0.38461538, 0.33333333],
       [0.26666667, 0.33333333, 0.12820513, 0.        ],
       [0.2       , 0.22222222, 0.20512821, 0.06666667],
       [0.2       , 0.22222222, 0.17948718, 0.        ],
       [0.3       , 0.38888889, 0.23076923, 0.13333333],
       [0.36666667, 0.38888889, 0.53846154, 0.4       ],
       [0.16666667, 0.55555556, 0.38461538, 0.33333333],
       [0.36666667, 0.77777778, 0.38461538, 0.4       ],
       [0.6       , 0.61111111, 0.43589744, 0.33333333],
       [0.46666667, 0.16666667, 0.35897436, 0.2       ],
       [0.23333333, 0.55555556, 0.28205128, 0.2       ],
       [0.2       , 0.27777778, 0.25641026, 0.2       ],
       [0.2       , 0.33333333, 0.35897436, 0.13333333],
       [0.4       , 0.55555556, 0.41025641, 0.26666667],
       [0.3       , 0.33333333, 0.25641026, 0.13333333],
       [0.03333333, 0.16666667, 0.07692308, 0.        ],
       [0.23333333, 0.38888889, 0.30769231, 0.2       ],
       [0.26666667, 0.55555556, 0.30769231, 0.13333333],
       [0.26666667, 0.5       , 0.30769231, 0.2       ],
       [0.43333333, 0.5       , 0.33333333, 0.2       ],
       [0.06666667, 0.27777778, 0.        , 0.06666667],
       [0.26666667, 0.44444444, 0.28205128, 0.2       ],
       [0.46666667, 0.72222222, 0.76923077, 1.        ],
       [0.3       , 0.38888889, 0.53846154, 0.6       ],
       [0.73333333, 0.55555556, 0.74358974, 0.73333333],
       [0.46666667, 0.5       , 0.66666667, 0.53333333],
       [0.53333333, 0.55555556, 0.71794872, 0.8       ],
       [0.9       , 0.55555556, 0.92307692, 0.73333333],
       [0.        , 0.27777778, 0.38461538, 0.46666667],
       [0.8       , 0.5       , 0.84615385, 0.53333333],
       [0.6       , 0.27777778, 0.71794872, 0.53333333],
       [0.76666667, 0.88888889, 0.79487179, 1.        ],
       [0.53333333, 0.66666667, 0.53846154, 0.66666667],
       [0.5       , 0.38888889, 0.58974359, 0.6       ],
       [0.63333333, 0.55555556, 0.64102564, 0.73333333],
       [0.26666667, 0.27777778, 0.51282051, 0.66666667],
       [0.3       , 0.44444444, 0.53846154, 0.93333333],
       [0.5       , 0.66666667, 0.58974359, 0.86666667],
       [0.53333333, 0.55555556, 0.64102564, 0.53333333],
       [0.93333333, 1.        , 0.94871795, 0.8       ],
       [0.93333333, 0.33333333, 1.        , 0.86666667],
       [0.36666667, 0.11111111, 0.51282051, 0.33333333],
       [0.66666667, 0.66666667, 0.69230769, 0.86666667],
       [0.23333333, 0.44444444, 0.48717949, 0.66666667],
       [0.93333333, 0.44444444, 0.94871795, 0.66666667],
       [0.46666667, 0.38888889, 0.48717949, 0.53333333],
       [0.6       , 0.72222222, 0.69230769, 0.73333333],
       [0.76666667, 0.66666667, 0.76923077, 0.53333333],
       [0.43333333, 0.44444444, 0.46153846, 0.53333333],
       [0.4       , 0.55555556, 0.48717949, 0.53333333],
       [0.5       , 0.44444444, 0.66666667, 0.73333333],
       [0.76666667, 0.55555556, 0.71794872, 0.4       ],
       [0.83333333, 0.44444444, 0.79487179, 0.6       ],
       [1.        , 1.        , 0.87179487, 0.66666667],
       [0.5       , 0.44444444, 0.66666667, 0.8       ],
       [0.46666667, 0.44444444, 0.53846154, 0.33333333],
       [0.4       , 0.33333333, 0.66666667, 0.26666667],
       [0.93333333, 0.55555556, 0.79487179, 0.86666667],
       [0.46666667, 0.77777778, 0.66666667, 0.93333333],
       [0.5       , 0.61111111, 0.64102564, 0.53333333],
       [0.36666667, 0.55555556, 0.46153846, 0.53333333],
       [0.66666667, 0.61111111, 0.61538462, 0.73333333],
       [0.6       , 0.61111111, 0.66666667, 0.93333333],
       [0.66666667, 0.61111111, 0.53846154, 0.86666667],
       [0.3       , 0.38888889, 0.53846154, 0.6       ],
       [0.63333333, 0.66666667, 0.74358974, 0.86666667],
       [0.6       , 0.72222222, 0.69230769, 1.        ],
       [0.6       , 0.55555556, 0.56410256, 0.86666667],
       [0.46666667, 0.27777778, 0.51282051, 0.6       ],
       [0.53333333, 0.55555556, 0.56410256, 0.66666667],
       [0.43333333, 0.77777778, 0.61538462, 0.86666667],
       [0.33333333, 0.55555556, 0.53846154, 0.53333333]])

In [14]:
y = y.values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

# NOW we implement the model

In [15]:
def Logistic(x, y, w, b, alpha, iters):
    
    m,n = x.shape
    
    for iter in range(iters):
        
        dj_dw = np.zeros(n)
        dj_db = 0
        
        for i in range(m):
            z = np.dot(x[i], w) + b
            y_pred = 1/(1 + np.exp(-z))
            
            for j in range(n):
                dj_dw[j] = dj_dw[j] + (y_pred - y[i])*x[i][j]
            
            dj_db = dj_db + (y_pred - y[i])
        
        dj_dw = dj_dw/m
        dj_db = dj_db/m
        
        w = w - alpha*dj_dw
        b = b - alpha*dj_db
    
    return w,b

In [16]:
alpha = 0.01
iters = 1000
w = np.zeros(x.shape[1])
b = 0

w,b = Logistic(x, y, w, b, alpha, iters)
print(f"features w: {w} and b:{b}")

features w: [-0.23969247  0.00627604 -0.49424361 -0.81547572] and b:0.48504955471789957

In [17]:
def predict(x, w, b):
    y = []
    for i in range(x.shape[0]):
        z = np.dot(x[i], w) + b
        y_pred = 1/(1 + np.exp(-z))
        y.append(y_pred)
    return y

In [18]:
x = np.array([[0.65, 0.44, 0.89, 0.63],
     [0.39, 0.87, 0.46, 0.33],
     [0.70, 0.45, 0.33, 0.70]])


y = predict(x, w, b)

In [19]:
y

[0.3494140946945553, 0.4751631081307582, 0.39799067589320264]

# Now we performe train test

In [20]:
df = pd.read_csv("iris.csv")

In [21]:
df = df.loc[df['Species']!='Iris-setosa']

In [22]:
df.loc[df['Species'] == "Iris-virginica", "Species"] = 0
df.loc[df["Species"] == "Iris-versicolor", "Species"] = 1

In [23]:
x = df.iloc[:,1:5]
x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
50             7.0           3.2            4.7           1.4
51             6.4           3.2            4.5           1.5
52             6.9           3.1            4.9           1.5
53             5.5           2.3            4.0           1.3
54             6.5           2.8            4.6           1.5
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[100 rows x 4 columns]

In [24]:
x.shape

(100, 4)

In [25]:
x = (x - x.min())/(x.max() - x.min())

In [26]:
x_train = df.iloc[20:80,1:5]
# x_train.reset_index(drop=True, inplace = True)
x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
70             5.9           3.2            4.8           1.8
71             6.1           2.8            4.0           1.3
72             6.3           2.5            4.9           1.5
73             6.1           2.8            4.7           1.2
74             6.4           2.9            4.3           1.3
75             6.6           3.0            4.4           1.4
76             6.8           2.8            4.8           1.4
77             6.7           3.0            5.0           1.7
78             6.0           2.9            4.5           1.5
79             5.7           2.6            3.5           1.0
80             5.5           2.4            3.8           1.1
81             5.5           2.4            3.7           1.0
82             5.8           2.7            3.9           1.2
83             6.0           2.7            5.1           1.6
84             5.4           3.0            4.5           1.5
85             6.0           3.4            4.5           1.6
86             6.7           3.1            4.7           1.5
87             6.3           2.3            4.4           1.3
88             5.6           3.0            4.1           1.3
89             5.5           2.5            4.0           1.3
90             5.5           2.6            4.4           1.2
91             6.1           3.0            4.6           1.4
92             5.8           2.6            4.0           1.2
93             5.0           2.3            3.3           1.0
94             5.6           2.7            4.2           1.3
95             5.7           3.0            4.2           1.2
96             5.7           2.9            4.2           1.3
97             6.2           2.9            4.3           1.3
98             5.1           2.5            3.0           1.1
99             5.7           2.8            4.1           1.3
100            6.3           3.3            6.0           2.5
101            5.8           2.7            5.1           1.9
102            7.1           3.0            5.9           2.1
103            6.3           2.9            5.6           1.8
104            6.5           3.0            5.8           2.2
105            7.6           3.0            6.6           2.1
106            4.9           2.5            4.5           1.7
107            7.3           2.9            6.3           1.8
108            6.7           2.5            5.8           1.8
109            7.2           3.6            6.1           2.5
110            6.5           3.2            5.1           2.0
111            6.4           2.7            5.3           1.9
112            6.8           3.0            5.5           2.1
113            5.7           2.5            5.0           2.0
114            5.8           2.8            5.1           2.4
115            6.4           3.2            5.3           2.3
116            6.5           3.0            5.5           1.8
117            7.7           3.8            6.7           2.2
118            7.7           2.6            6.9           2.3
119            6.0           2.2            5.0           1.5
120            6.9           3.2            5.7           2.3
121            5.6           2.8            4.9           2.0
122            7.7           2.8            6.7           2.0
123            6.3           2.7            4.9           1.8
124            6.7           3.3            5.7           2.1
125            7.2           3.2            6.0           1.8
126            6.2           2.8            4.8           1.8
127            6.1           3.0            4.9           1.8
128            6.4           2.8            5.6           2.1
129            7.2           3.0            5.8           1.6

In [27]:
y_train = df.iloc[20:80, -1]
# y_train.reset_index(drop=True, inplace = True)
y_train

70     1
71     1
72     1
73     1
74     1
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     1
92     1
93     1
94     1
95     1
96     1
97     1
98     1
99     1
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
Name: Species, dtype: object

In [28]:
x_test = df.iloc[1:20, 1:5]
x_test

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
51            6.4           3.2            4.5           1.5
52            6.9           3.1            4.9           1.5
53            5.5           2.3            4.0           1.3
54            6.5           2.8            4.6           1.5
55            5.7           2.8            4.5           1.3
56            6.3           3.3            4.7           1.6
57            4.9           2.4            3.3           1.0
58            6.6           2.9            4.6           1.3
59            5.2           2.7            3.9           1.4
60            5.0           2.0            3.5           1.0
61            5.9           3.0            4.2           1.5
62            6.0           2.2            4.0           1.0
63            6.1           2.9            4.7           1.4
64            5.6           2.9            3.6           1.3
65            6.7           3.1            4.4           1.4
66            5.6           3.0            4.5           1.5
67            5.8           2.7            4.1           1.0
68            6.2           2.2            4.5           1.5
69            5.6           2.5            3.9           1.1

In [29]:
y_test = df.iloc[1:20, -1]
y_test

51    1
52    1
53    1
54    1
55    1
56    1
57    1
58    1
59    1
60    1
61    1
62    1
63    1
64    1
65    1
66    1
67    1
68    1
69    1
Name: Species, dtype: object

In [30]:
y_train.shape

(60,)

In [31]:
x_train.shape

(60, 4)

In [32]:
x_train = x_train.values
y_train = y_train.values

In [33]:
x_train[0]

array([5.9, 3.2, 4.8, 1.8])

In [34]:
alpha = 0.01
iters = 1000
w = np.zeros(x_train.shape[1])
b = 0

w,b = Logistic(x_train, y_train, w, b, alpha, iters)
print(f"features w: {w} and b:{b}")

features w: [ 0.66025067  0.5946957  -0.99978733 -0.79520894] and b:0.31862237025814694

In [35]:
def predict(x, w, b):
    y = []
    for i in range(x.shape[0]):
        z = np.dot(x[i], w) + b
        y_pred = 1/(1 + np.exp(-z))
        
        if y_pred >= 0.5:
            y_pred = 1
        else:
            y_pred = 0
        y.append(y_pred)
    return y

x_test = x_test.values
y_pred = predict(x_test, w, b)

In [36]:
y_pred

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [37]:
y_test

51    1
52    1
53    1
54    1
55    1
56    1
57    1
58    1
59    1
60    1
61    1
62    1
63    1
64    1
65    1
66    1
67    1
68    1
69    1
Name: Species, dtype: object